### ISSUE TITLE
GUI: mehrfache Ausgabeformate vom RAM

### ISSUE THREAD

**Issue by vogel-jo** [HERDER2014/CPUSim#1]
GUI:
wie wärs, wenn wir zum RAM-dingens noch einen disassembler dazu packen? also so, dass man wählen kann zwischen zahlen und assember-code.
das wär glaube ich recht fresh.

**Comment by jacobsjo** [comment]
Wir haben uns heute dagegenentschieden: Einfaches anklicken der Position im ram zeigt code position in quelltext an -> zur uebersicht dafuer ein neuer Issue
