### ISSUE TITLE
Initiale Position von BP und SP

### ISSUE THREAD

**Issue by jacobsjo** [HERDER2014/CPUSim#18]
Hallo Jungs,

habe euer Projekt erfolgreich mit dem diesjährigen LK angewendet und werde es auch in Zukunft tun. Auch 2 Jahre später noch einmal, DICKES LOB: TOP-LEISTUNG.

Nun zu meinem eigentlichen Anliegen. Die Entscheidung, den BP und SP initial auf VP-1 (-8Bit) zu setzen ist bei einem 16 Bit Stack blöd. Ein relativer Zugriff (z.B. MOV AX,[BP+xx]) auf den Stack über den BP bedeutet dann immer eine ungeradzahlige Addition (Subtraktion) von Byte.

Im derzeitigen Kurs haben wir dies im Quellcode einfach geändert. Es betraf nur die unit uCPU, bei der die Zeilen 216 und 217 in

```Pascal
Reg.SP := r.GetVRAMStart;
Reg.BP := r.GetVRAMStart;
```

und die Zeilen 423-433 wie folgt

```Pascal
procedure TCPU.push(w: word);
begin
  Reg.SP -= 2;
  Ram.WriteWord(Reg.SP, w);
end;
```

```Pascal
function TCPU.pop(): word;
begin
  Result := Ram.ReadWord(Reg.SP);
  Reg.SP += 2;
end;
```

geändert werden müssten.

Für eure Beispielprogramme hätte dies natürlich auch Konsequenzen, welche ich derzeit nicht mehr alle zusammen bekomme.

Im derzeitigen Kurs haben wir die Stellen einfach geändert.
Auf Grund euer sehr guten Strukturierung, war das Finden der entsprechenden Stellen ein Kinderspiel.

Ich denke, es wäre eine sinnvolle Änderung, welche ihr übernehmen solltet (auch wenn dadurch noch einmal kurzfristig Arbeit in die Beispielprogramme gesteckt werden muss, obwohl: s. Anlagen).

In der Hoffnung, dass es euch allen gut geht
verbleibt
M. Nuck 

--- Anlagen --- (als txt weil Github aus irgendeinem Grund Dateitypbeschränkungen hat)
[db Ausgabe.asm.txt](https://github.com/HERDER2014/CPUSim/files/877118/db.Ausgabe.asm.txt)
[mehrstellige Ausgabe.asm.txt](https://github.com/HERDER2014/CPUSim/files/877121/mehrstellige.Ausgabe.asm.txt)
[mehrstellige Eingabe.asm.txt](https://github.com/HERDER2014/CPUSim/files/877119/mehrstellige.Eingabe.asm.txt)
[snake.asm.txt](https://github.com/HERDER2014/CPUSim/files/877120/snake.asm.txt)

**Comment by Nik-Sch** [comment]
Ich würde mir das am Wochenende mal angucken, wenn ich Zeit finde.
