### ISSUE TITLE
Compiler: Parsen von String

### ISSUE THREAD

**Issue by LeonardKoenig** [HERDER2014/CPUSim#5]
Hab mir's nochmal ueberlegt mit dem Parsen des Strings: Ein String ist in Laz. afaik auf 256 Shortstrings limitiert. Ist also nicht so praktisch... . Ist es fuer euch ok, wenn wir euch ein file uebergeben?

**Comment by jacobsjo** [comment]
Wiebitte? Ein Shortsting ist ein String mit 255 characters! Aus irgendeinem grund interpetiert Lazarus String als Shortstring. Du kannst auch einfach AnsiString (Ascii) oder UnicodeString (Unicode) benutzen, Diese haben keine beschraenkung ... (einfach mal Googlen)

**Comment by LeonardKoenig** [comment]
Warum gibt's fuer sowas keine Verweise id. Dokumentation?!? FUCK LAZ...^^

bin trotzdem fuers uebergeben eines files

**Comment by vogel-jo** [comment]
Falsch, wir kompilieren mit {$H+} (String = AnsiString), daher kann jeder String beliebig groß sein.
Übergeben einer Datei halte ich für eine Verschwendung von Rechenzeit, denn dann haben wir die Eingabe einmal im Speicher in dem Memo oder was auch immer, dann wird das in die Datei geschrieben, und dann wird vom Compiler die Datei wieder geöffnet und eingelesen. Unnötiger Festplattenzugriff. Wäre wenn überhaupt eher für eine zeilenweise Übergabe.

**Comment by LeonardKoenig** [comment]
ok, wenn der beliebig gross sein darf, dann ist das ok
