### ISSUE TITLE
GUI: TActions nutzen um code aufzuraeumen.

### ISSUE THREAD

**Issue by LeonardKoenig** [HERDER2014/CPUSim#7]

**Comment by jacobsjo** [comment]
ist das noch immer aktuell oder kann das geschlossen werden?

**Comment by LeonardKoenig** [comment]
immernoch aktuell, habe heute sogar schon damit angefangen. Man kann dann sogar ein paar per Hand gecodete Tastenkombis rausnehmen. Ist aber noch nicht fertig (u.A. ist die "wirklich schliessen" abfrage dadurch verschwunden)
